/*
	ArmA 3 King of Hill
	Code written by Sa-Matra
	Using this code without Sa-Matra's direct permission is forbidden
	
	Special build for Gamed.de
	
	Build ETYKMBSIGDHGNALL
*/
#include "defines.hpp"
#define kgv5t1	30
#define kgy1s8	30
#define kg3isv	30
kgw6m8={daytime>20||daytime<3};
kgy9dn={_this=toArray(format["%1",_this]);
_this set[0,32];
_this set[count _this-1,32];
_this=toString _this;
private "_0ga";
_0ga="EmptyDetector" createVehicleLocal[0,0,0];
_0ga setTriggerArea[0,0,0,false];
_0ga setTriggerStatements[_this,"",""];
_0ga};
kg51kr={if(count kgmbui>0)then{{_x call kg9824}forEach kgmbui;
kgmbui resize 0;
};
};
kgweyr={private["_0pg","_0ho","_0io","_0jo"];
_0pg=_this select 0;
_0ho=_this select 1 select 0;
_0io=_this select 1 select 1;
_0jo=_this select 1 select 2;
if(_0jo>=0&&(_0pg select 2>_0jo))exitWith{false};
sqrt(((_0ho select 0)-(_0pg select 0))^2+((_0ho select 1)-(_0pg select 1))^2)<_0io};
kg4izk={if(_this=="HitHull")exitWith{0.1};
if(_this=="HitBody")exitWith{0.1};
if(_this=="HitEngine")exitWith{0.5};
if(_this=="HitFuel")exitWith{0.5};
if(_this=="HitHRotor")exitWith{0.4};
if(_this=="HitVRotor")exitWith{0.4};
if(toLower _this find toLower "Engine">=0)exitWith{0.5};
if(toLower _this find toLower "Turret">=0)exitWith{0.5};
if(toLower _this find toLower "Gun">=0)exitWith{0.5};
if(toLower _this find toLower "Track">=0)exitWith{0.5};
if(toLower _this find toLower "Wheel">=0)exitWith{0.5};
};
kg4fy2={if(_this=="HitHull")exitWith{8};
if(_this=="HitBody")exitWith{8};
if(_this=="HitEngine")exitWith{8};
if(_this=="HitFuel")exitWith{8};
if(_this=="HitHRotor")exitWith{10};
if(_this=="HitVRotor")exitWith{8};
if(toLower _this find toLower "Engine">=0)exitWith{3};
if(toLower _this find toLower "Turret">=0)exitWith{8};
if(toLower _this find toLower "Gun">=0)exitWith{8};
if(toLower _this find toLower "Track">=0)exitWith{25};
if(toLower _this find toLower "Wheel">=0)exitWith{8};
};
kgoy8n={(getAllHitPointsDamage _this)params["_0ko","_sels","_0lo","_08c"];
if(isNil{_0ko})exitWith{0};
_08c=0;
{if(_0lo select _forEachIndex>_x call kg4izk)then{_08c=_08c+(_x call kg4fy2);
};
}forEach _0ko;
_08c};
kgwkl8={(getAllHitPointsDamage _this)params["_0ko","_sels","_0lo"];
if(isNil{_0ko})exitWith{false};
scopeName "search";
{if(_0lo select _forEachIndex>_x call kg4izk)exitWith{true breakOut "search";
};
}forEach _0ko;
false;
};
kg592p={if(local _this)then{kgy5ql=0;
};
if(_this isKindOf "Plane")then{_this setDamage(1/3);
};
(getAllHitPointsDamage _this)params["_0ko","_sels","_0lo"];
{if(_0lo select _forEachIndex>_x call kg4izk)then{_this setHitIndex[_forEachIndex,_x call kg4izk];
};
}forEach _0ko;
if(fuel _this<0.01)then{_this setFuel 0.06+random 0.02;
};
_this setVelocity[0,0,0.5];
};

#define kgx3nt 1.5
kgxhpo={kgv9bx=createLocation["Name",kgdva1,kg7vk8,kgu85m];
kgv9bx setRectangular kgmhlg;
kgv9bx setDirection kg12rz;
_0mo=kg7vk8 min kgu85m;
kgetly=createLocation["Name",kgdva1,kg7vk8+_0mo*kgx3nt,kgu85m+_0mo*kgx3nt];
kgetly setRectangular kgmhlg;
kgetly setDirection kg12rz;
kgx5lt=[];
kgtou3=[];
kg79q5=[];
for "_i" from 0 to count(kgubgt)-1 do{kgtou3 set[_i,createLocation["Name",kgmksk select _i,kg6rhv,kg6rhv]];
kgx5lt set[_i,createLocation["Name",kgz9yy select _i,kgh5it,kgh5it]];
kg79q5 set[_i,createLocation["Name",kgpli7 select _i,kgtbgi,kgwuoy]];
(kg79q5 select _i)setDirection(kgzdcu select _i);
};
};
kgfnsu={if(_this select 2>kgiocv)exitWith{false};
_this in kgv9bx};
kg5dty={private "_0no";
_0no=_this getVariable["koh_safe",-1];
if(_0no>0&&serverTime>_0no)exitWith{true};
false;
};
kgw53f={private "_0ia";
_0ia=getPosATL _this;
if((_0ia select 2)>kgo1qf)exitWith{false};
private "_0c";
_0c=kgubgt find(_this getVariable["koh_side",civilian]);
if(_0c<0)exitWith{false};
if!(_0ia in(kg79q5 select _0c))exitWith{false};
private "_0ja";
_0ja=_this getVariable["koh_safe",-1];
if(_0ja<serverTime&&_0ja>0)exitWith{true};
if(_0ia select 2>kgrnud)exitWith{false};
if(_0ia in(kgx5lt select _0c))exitWith{true};
if(_0ia in(kgtou3 select _0c))exitWith{true};
false};
kgjvx9={private "_0ia";
_0ia=getPosATL _this;
if((_0ia select 2)>kgrnud)exitWith{false};
private "_0c";
_0c=kgubgt find(_this getVariable["koh_side",civilian]);
if(_0c<0)exitWith{false};
_0ia in(kgx5lt select _0c)};
kg9ynt={private["_0f","_0oo","_0po","_0qo","_0ro","_0so"];
_0f=_this select 0;
_0oo=_this select 1;
_0po=_this select 2;
_0qo=_0po call kg2mal;
_0ro=-1;
for "_i" from 0 to count(kgrh3c)-1 do{if(kgrh3c select _i select 0==_0f)exitWith{_0ro=_i;
};
};
if(_0ro==-1)then{_0ro=count(kgrh3c);
kgrh3c set[_0ro,[_0f,[]]];
};
_0so=kgrh3c select _0ro select 1;
_0so set[_0oo,_0qo];
};
kg3wio={if(kgpaxb)exitWith{};
if(count(kgrh3c)>0)then{kg9knh=kgrh3c;
publicVariable "kg9knh";
call kgypcm;
kgrh3c=[];
};
};
kgypcm={kg9knh call kgyn98;
if(isServer)then{kgvchw=kgvchw+kg9knh;
if(count(kgvchw)>kgv5t1)then{private["_0to"];
kgiqgz=kgiqgz+1;
_0to=format["publicVar_shared_texturedSimpleListArchive%1",kgiqgz];
missionNamespace setVariable[_0to,kgvchw];
kg75r3 set[count kg75r3,_0to];
kgvchw=[];
publicVariable _0to;
publicVariable "kg75r3";
};
publicVariable "kgvchw";
};
kg9knh=[];
};
kgyn98={{if(!isNull(_x select 0))then{for "_i" from 0 to count(_x select 1)-1 do{if(!isNil{_x select 1 select _i})then{(_x select 0)setObjectTexture[_i,kgnfhp select(_x select 1 select _i)];
};
};
};
}forEach _this;
};
kg2mal={private["_0c"];
_0c=-1;
for "_i" from 0 to count(kgnfhp)-1 do{if(kgnfhp select _i==_this)exitWith{_0c=_i;
};
};
if(_0c==-1)then{_0c=count(kgnfhp);
kgnfhp set[_0c,_this];
publicVariable "kgnfhp";
};
_0c};
kgqjd2={private["_0f","_0uo"];
_0f=_this select 0;
_0uo=_this select 1;
if(_0f in kgeeks)then{if(_0uo)then{kgeeks=kgeeks-[_0f];
};
}else{if(!_0uo)then{kgeeks set[count kgeeks,_0f];
};
};
};
kgdslk={if(kgxjs5)exitWith{};
if(count(kgeeks)>0)then{kg8n3l=kgeeks;
publicVariable "kg8n3l";
call kgg65o;
kgeeks=[];
};
};
kgg65o={{_x allowDamage false;
}forEach kg8n3l;
if(isServer)then{kgruzk=kgruzk-[objNull]+kg8n3l;
if(count(kgruzk)>kgy1s8)then{private["_0to"];
kgw1fg=kgw1fg+1;
_0to=format["publicVar_shared_invincibleSimpleListArchive%1",kgw1fg];
missionNamespace setVariable[_0to,kgruzk];
kgnlkj set[count kgnlkj,_0to];
kgruzk=[];
publicVariable _0to;
publicVariable "kgnlkj";
};
};
kg8n3l=[];
};
kgexnd={private["_0f","_0uo"];
_0f=_this select 0;
_0uo=_this select 1;
if(_0f in kgedok)then{if(_0uo)then{kgedok=kgedok-[_0f];
};
}else{if(!_0uo)then{kgedok set[count kgedok,_0f];
};
};
};
kggmuo={if(kgeyi9)exitWith{};
if(count(kgedok)>0)then{kgj2c8=kgedok;
publicVariable "kgj2c8";
call kgfuqa;
kgedok=[];
};
};
kgfuqa={{_x enableSimulation false;
_x setVelocity[0,0,0];
}forEach kgj2c8;
if(isServer)then{kg7w7m=kg7w7m-[objNull]+kgedok;
if(count(kg7w7m)>kg3isv)then{private["_0to"];
kg65kr=kg65kr+1;
_0to=format["publicVar_shared_simulationSimpleListArchive%1",kg65kr];
missionNamespace setVariable[_0to,kg7w7m];
kgcq5i set[count kgcq5i,_0to];
kg7w7m=[];
publicVariable _0to;
publicVariable "kgcq5i";
};
};
kgj2c8=[];
};
kg3uuq={if!(_this in kg6ipw)then{kg6ipw set[count kg6ipw,_this];
};
};
kgzrp9={if(count(kg6ipw)>0)then{kg6hor=kg6ipw;
publicVariable "kg6hor";
call kgszfv;
kg6ipw=[];
};
};
kgffxz={private["_0ec","_i"];
_0ec=typeOf(_this);
_i=(kgxm4g select 0)find _0ec;
if(_i==-1)then{_i=count(kgxm4g select 0);
(kgxm4g select 0)set[_i,_0ec];
(kgxm4g select 1)set[_i,_0ec call kgi6i6];
};
kgxm4g select 1 select _i};
kgi6i6={private["_0vo","_0wo","_0xo","_0mb"];
_0vo=[];
_0wo=[];
_0xo={for "_i" from 0 to count(_this)-1 do{_0yo=configName(_this select _i);
_01e=getText((_this select _i)>>"name");
if(_0wo find _01e==-1)then{_0vo set[count _0vo,_0yo];
_0wo set[count _0wo,_01e];
};
};
};
_0mb=configFile>>"CfgVehicles">>_this;
for "_i" from 0 to 10 do{if(_i>0)then{_0mb=inheritsFrom _0mb};
if(!isClass(_0mb))exitWith{};
if(isClass(_0mb>>"HitPoints"))then{(_0mb>>"HitPoints")call _0xo;
private["_0nb"];
_0nb=_0mb>>"turrets";
for "_i" from 0 to(count _0nb-1)do{private["_0ob","_0pb"];
_0ob=_0nb select _i;
_0pb=_0ob>>"turrets";
(_0ob>>"HitPoints")call _0xo;
for "_j" from 0 to(count _0pb-1)do{((_0pb select _j)>>"HitPoints")call _0xo;
};
};
};
};
if(_this isKindOf "CAManBase")then{{_0wo set[count _0wo,_x select 0];
_0vo set[count _0vo,_x select 1];
}forEach[["leg_l","HitLegs"],["hand_l","HitHands"]];
};
[_0wo,_0vo]};
kgxkcq={private["_0nb","_0sb"];
_0nb=configFile>>"CfgVehicles">>typeOf(_this)>>"turrets";
_0sb=[];
for "_i" from 0 to(count _0nb-1)do{private["_0ob","_0pb"];
_0ob=_0nb select _i;
_0pb=_0ob>>"turrets";
_0sb=_0sb+[[_i]];
for "_j" from 0 to(count _0pb-1)do{private["_0qb"];
_0qb=_0pb select _j;
_0sb=_0sb+[[_i,_j]];
};
};
_0sb};
kgrgrc={if(isNull _this)exitWith{format["getVehicleCrew called with null vehicle!"]call kgkq1c;
[[],objNull]};
private["_0sb","_0tb","_0ba","_0ub","_0vb"];
if(isNil{_this getVariable "koh_turrets"})then{_this setVariable["koh_turrets",_this call kgxkcq];
};
_0sb=_this getVariable "koh_turrets";
_0tb=[];
{_0tb set[count _0tb,_this turretUnit _x];
}forEach _0sb;
_0ub=driver _this;
_0vb=[];
{if(alive _x)then{_0vb pushBack _x;
};
}forEach((crew _this)-[_0ub]-_0tb);
if(!alive _0ub)then{_0ub=objNull;
};
_0ba=[_0vb,_0ub];
{_0ba pushBack(if(alive _x)then{_x}else{objNull});
}forEach _0tb;
_0ba};
kg1gil={private["_0ba","_01b","_02b"];
if(_this select 0==_this select 1)exitWith{true};
_0ba=false;
_01b=(if(isNil{_this select 2})then{"CfgWeapons"}else{_this select 2});
_02b=configFile>>_01b>>(_this select 0);
for "_i" from 0 to 4 do{if(!isNil{_02b})then{_02b=inheritsFrom(_02b);
if(configName(_02b)==_this select 1)exitWith{_0ba=true;
};
};
};
_0ba};
kg374s={{if([_this,_x]call kg1gil)exitWith{1};
}count["CarHorn","SmokeLauncher"]==0;
};
kg49yr={private["_0zo","_0ba","_0sb"];
_0zo={if(_x call kg374s)exitWith{1}};
_0ba=[false,_0zo count(_this weaponsTurret[-1])==1];
if(isNil{_this getVariable "koh_turrets"})then{_this setVariable["koh_turrets",_this call kgxkcq];
};
_0sb=_this getVariable "koh_turrets";
{_0ba set[count _0ba,_0zo count(_this weaponsTurret _x)==1];
}forEach _0sb;
_0ba};
kgmwxh={private["_0ya","_01o","_0ba"];
_0ya=_this call kgrgrc;
if(isNil{_this getVariable "koh_canfire"})then{_this setVariable["koh_canfire",_this call kg49yr];
};
_01o=_this getVariable "koh_canfire";
_0ba=[];
for "_i" from 1 to count(_0ya)-1 do{if(_01o select _i)then{if(!isNull(_0ya select _i))then{_0ba set[count _0ba,_0ya select _i];
};
};
};
_0ba};
kgcsod={if(count(crew _this)>1)then{_02o=_this call kgmwxh;
if(count(_02o)!=1)then{effectiveCommander _this}else{_02o select 0};
}else{effectiveCommander _this}};
kg8tf3={private["_05d","_03o","_04o","_0vo"];
_05d=(_this select 0);
_03o=(_this select 1);
_04o=(_this select 2);
if(_03o==""||_03o=="?")exitWith{""};
_0vo=_05d call kgffxz;
_i=(_0vo select 0)find _03o;
if(_i!=-1)exitWith{(_0vo select 1 select _i)};
""};
kgokdu={
#define kgvmfd	(if(_05o < 0) then {damage _0f} else {_0f getHitIndex _05o})
params["_0f","_03o","_09o","_0uh","_with","_05o","_06o"];
if(isNull _06o)then{_06o=_0uh call kgcsod;
};
if(_0f call kg5dty)exitWith{kgvmfd;
};
if(!(isServer&&isDedicated))then{if(_0f==vehicle player)then{if(_this call kg8tf3=="HitHRotor")then{kgy5ql=(_this select 2);
};
};
};
if(_0uh isKindOf "ParachuteBase")exitWith{kgvmfd;
};
private _07o=_0f==player;
if(_07o&&(isNull _0uh||player==_0uh)&&kgv74f)exitWith{kgvmfd;
};
if(_07o&&kg61p9>diag_tickTime)exitWith{kgvmfd;
};
if((_07o||player in _0f)&&side group _06o==side group player&&getNumber(configFile>>"CfgVehicles">>typeOf _0uh>>"artilleryScanner")>0)exitWith{kgb64s=true;
_08o=_09o-kgvmfd;
kgvmfd+(0.25 min _08o);
};
if(_07o&&kgb64s&&(isNull _0uh||_0uh==player))exitWith{kgvmfd;
};
if(alive _0f)then{if(_05o==-1)then{if(player in _0f&&_0f!=player)then{if(!isNull _0uh)then{_0zl=(_09o-damage _0f);
if(_0zl>0.1)then{addCamShake[_0zl*20,3,15];
};
};
};
};
};
if(alive _0f&&!isNull _06o&&(_06o!=_0f))then{if!(_06o in(_this select 0))then{_0ap=(_this select 0)getVariable["koh_assists",[]];
_0nl=_06o getVariable["koh_owner",0];
if(_0nl==0)exitWith{};
if!(_0nl in _0ap)then{if(_0f isKindOf "Man")exitWith{_0ap set[count _0ap,_0nl];
_0f setVariable["koh_assists",_0ap,true];
};
_0bp=_0f getVariable["koh_damagelogs",[[],[],[]]];
if(true)then{_0cp=_05o<0;
_0dp=kgvmfd;
if(_0dp<1)then{_0zl=_09o-_0dp;
if(_0zl<=0)exitWith{};
_0ep=(_0bp select 0);
_0fp=(_0bp select 1);
_0gp=(_0bp select 2);
_i=_0ep find _06o;
if(_i==-1)then{_i=count(_0ep);
_0ep pushBack _06o;
_0fp pushBack(if(_0cp)then{_0zl}else{0});
_0gp pushBack(if(_0cp)then{0}else{_0zl});
}else{_0fp set[_i,(_0fp select _i)+(if(_0cp)then{_0zl}else{0})];
_0gp set[_i,(_0gp select _i)+(if(_0cp)then{0}else{_0zl})];
};
if((_0fp select _i>0.05)||(_0gp select _i>1.1))then{_0ap set[count _0ap,_0nl];
_0f setVariable["koh_assists",_0ap,true];
};
_0f setVariable["koh_damagelogs",_0bp];
};
};
};
};
};
_09o;
};
kgvoo3={if(diag_tickTime>(_this getVariable["in_hill_check",0])+5)then{_this setVariable["in_hill_check",diag_tickTime];
_this setVariable["in_hill",getPosWorld _this in kgetly];
};
_this getVariable["in_hill",false];
};
kgaatx={if(!isNil{_this getVariable "flares_index"})exitWith{_this getVariable["flares_index",-1];
};
private["_0c","_0ba"];
_0c=-1;
_0ba=-1;
{if(_x=="CMFlareLauncher")exitWith{_0c=_0c+1;
_0ba=_0c;
};
_0c=_0c+count(getArray(configFile>>"CfgWeapons">>_x>>"modes"));
}forEach(_this weaponsTurret[-1]);
_this setVariable["flares_index",_0ba];
_0ba};
kgcm9a={if(!isNil{_this getVariable "smokes_turret"})exitWith{_this getVariable["smokes_turret",nil];
};
_this setVariable["smokes_turret",(call{scopeName "search";
private["_0hp","_0mb","_0ip"];
_0hp=[];
_0mb=configFile>>"CfgVehicles">>typeOf(_this)>>"turrets";
for "_i" from 0 to count(_0mb)-1 do{_0hp set[0,_i];
if("SmokeLauncher" in(_this weaponsTurret _0hp))exitWith{_0hp breakOut "search";
};
_0ip=(_0mb select _i)>>"turrets";
for "_j" from 0 to count(_0ip)-1 do{_0hp set[1,_j];
if("SmokeLauncher" in(_this weaponsTurret _0hp))exitWith{_0hp breakOut "search";
};
};
_0hp resize 1;
};
nil})];
_this getVariable "smokes_turret";
};
kgpxug={if(!isNil{_this getVariable "smokes_index"})exitWith{_this getVariable["smokes_index",-1];
};
private["_0hp","_0c"];
_0hp=_this call kgcm9a;
_0c=-1;
_this setVariable["smokes_index",(call{scopeName "search";
{if(_x=="SmokeLauncher")exitWith{(_0c+1)breakOut "search";
};
_0c=_0c+count(getArray(configFile>>"CfgWeapons">>_x>>"modes"));
}forEach(_this weaponsTurret _0hp);
-1;
})];
_this getVariable "smokes_index";
};
kgpz1a={private["_0f","_09c"];
_0f=_this select 0;
_09c=_this select 2;
if(isServer)then{if(_0f getVariable["cleanup_empty_at",0]>0)then{_0f setVariable["cleanup_empty_at",0];
};
if(_0f getVariable["cleanup_delete_at",0]>0)then{_0f setVariable["cleanup_delete_at",0,true];
};
};
if(!hasInterface)exitWith{};
if(_09c getVariable["taxed_player",objNull]==_09c)exitWith{};
if!(_0f call kgvoo3)then{_0jp=_0f getVariable["taxi_passengers",[]];
_0jp set[count _0jp,_09c];
_0f setVariable["taxi_passengers",_0jp];
};
};
kgt6az={private["_0f","_09c"];
_0f=_this select 0;
_09c=_this select 2;
if(isServer)then{if({alive _x}count(crew _0f)==0)then{_0f setVariable["cleanup_empty_at",diag_tickTime];
};
};
if(!hasInterface)exitWith{};
if(_09c getVariable["taxed_player",objNull]==_09c)exitWith{};
_0jp=_0f getVariable["taxi_passengers",[]];
if(_09c in _0jp)then{_0jp=_0jp-[_09c];
_0f setVariable["taxi_passengers",_0jp];
if(_0f call kgvoo3)then{_0ap=false;
if((local _0f)&&(player in _0f))then{if(_0f isKindOf "Air")then{_08d=(getPosATL player)select 2;
if(_08d<=50||_08d>=100)then{if(_08d>=100)then{[[player getVariable["koh_owner",0],kg5pin]]call kgt98j;
}else{[[player getVariable["koh_owner",0],kgpv7v,call kg5coq]]call kgt98j;
_0ap=true;
};
};
}else{[[player getVariable["koh_owner",0],kgj2t2,call kg5coq]]call kgt98j;
_0ap=true;
};
};
_09c setVariable["taxed_player",_09c];
if(_0ap)then{_09c setVariable["koh_assisted_by",player getVariable["koh_owner",0],true];
};
};
};
};
kghb1e=[];
kgnn3w=[];
kgnklp={private["_0f","_07b"];
_0f=_this select 0;
_0xh=_this select 1;
_0kp=_this select 2;
_03l=_this select 5;
_07b=_this select 6;
if(_0xh=="SmokeLauncher")then{kga73j=true;
if(effectiveCommander _0f==player)then{kgrvge=[_0f,_this select 4];
publicVariable "kgrvge";
};
};
if(local _07b)then{if(player in _0f||player==_0f)then{if((vehicle player)call kg5dty)then{switch(true)do{case((_0f!=player)&&!(_0xh in["CMFlareLauncher","SmokeLauncher"])):{["警告","车辆不得在安全区内射击。",false,6]call kgumf6;
deleteVehicle _07b;
};
case(_0xh=="Put"):{["禁止在安全区安放炸药包。找死呢？","<img image='i\nofun.paa' size='7'/>",false,8]call kgumf6;
deleteVehicle _07b;
};
if(_07b call kgjdt5)then{["警告","在安全区不允许使用引导式发射器。",false,6]call kgumf6;
deleteVehicle _07b;
};
};
};
if(isNull(_07b))exitWith{};
if(player==_0f)then{if(!isNull(_07b))then{switch(true)do{case(_0kp=="SmokeShellMuzzle"):{if(player call kgjvx9)then{["警告","基地内禁止吸烟",false,6]call kgumf6;
deleteVehicle _07b;
};
};
case(_03l=="HandGrenade"):{_0na=[_07b];
{if(alive _x)then{_0na set[count _0na,_x]};
}forEach kgbkl7;
kgbkl7=_0na;
kgc35q=[_07b,playerSide];
publicVariable "kgc35q";
};
};
};
};
if(_07b call kgjdt5)then{for "_i" from 0 to count(kggmp7)-1 do{_0c=kggmp7 find objNull;
if(_0c<0)exitWith{};
kggmp7 deleteAt _0c;
kga2nf deleteAt _0c;
};
kggmp7 pushBack _07b;
kga2nf pushBack diag_tickTime;
}else{if(player==_0f)then{for "_i" from 0 to count(kghb1e)-1 do{_0c=kghb1e find objNull;
if(_0c<0)exitWith{};
kghb1e deleteAt _0c;
kgnn3w deleteAt _0c;
};
kghb1e pushBack _07b;
kgnn3w pushBack getPosWorld _07b;
};
};
if(kgj7su+10<diag_tickTime)then{if(cursorTarget isKindOf "LaserTarget")then{if(effectiveCommander _0f==player)then{_05n=cursorTarget getVariable["koh_lased_by",-1];
if(_05n>0)then{_0f setVariable["koh_laser_assist_by",_05n,true];
_0f setVariable["koh_laser_assist_at",serverTime,true];
kgj7su=diag_tickTime;
};
};
};
};
if(getNumber(configFile>>"CfgVehicles">>typeOf(_0f)>>"artilleryScanner")>0)then{_0mb=configFile>>"CfgAmmo">>typeOf(_07b);
(kg9fav select 0)pushBack _07b;
(kg9fav select 1)pushBack(if(isArray(_0mb>>"submunitionConeType")||getNumber(_0mb>>"submunitionCount")>1)then{""}else{getText(_0mb>>"submunitionAmmo")});
(kg9fav select 2)pushBack getPosWorld _07b;
(kg9fav select 3)pushBack getPosWorld _07b;
(kg9fav select 4)pushBack 0;
};
};
};
};
kgjdt5={(typeOf _this)call kgr77u;
};
kgr77u={private "_0mb";
_0mb=configFile>>"CfgAmmo">>_this;
if(getText(_0mb>>"simulation")!="shotMissile")exitWith{false};
if(getNumber(_0mb>>"irLock")>0)exitWith{true};
if(getNumber(_0mb>>"airLock")>0)exitWith{true};
if(getNumber(_0mb>>"maneuvrability")>0)exitWith{true};
false;
};
kgziqs={_0lp=_this addEventHandler["HandleDamage",{_this call kgokdu}];
_0mp=_this addEventHandler["Killed",{kguc3i=_this;
publicVariableServer "kguc3i";
_0f=_this select 0;
if!(_0f isKindOf "Man")then{kgmbui pushBack _0f;
};
}];
_0np=_this addEventHandler["Fired",{_this call kgnklp}];
_this setVariable["eh_hd",_0lp];
_this setVariable["eh_k",_0mp];
_this setVariable["eh_f",_0np];
if(!(_this isKindOf "Man"))then{_0op=_this addEventHandler["GetIn",{_this call kgpz1a}];
_0pp=_this addEventHandler["GetOut",{_this call kgt6az}];
_0qp=_this addEventHandler["IncomingMissile",{_this call kguu8d;
}];
_this setVariable["eh_gi",_0op];
_this setVariable["eh_go",_0pp];
_this setVariable["eh_im",_0qp];
};
};
kg9824={{_this removeEventHandler[_x select 0,_this getVariable[_x select 1,-1]];
}forEach[["HandleDamage","eh_hd"],["Killed","eh_k"],["GetIn","eh_gi"],["GetOut","eh_go"],["IncomingMissile","eh_im"],["Fired","eh_f"]];
};
kguu8d={if(!hasInterface)exitWith{};
if!((_this select 1)call kgr77u)exitWith{};
_05d=_this select 0;
if(player in _05d)then{if(_05d isKindOf "Air")then{if((local _05d)&&(kg65oi in kgge9y))then{_0c=_05d call kgaatx;
if(_0c>=0)then{_05d action["UseWeapon",_05d,(crew _05d)select 0,_0c];
};
};
}else{if(kg65oi in kgge9y)then{if(kgu1o7+50<diag_tickTime||kgmc8u vectorDistance getPosWorld _05d>100)then{_0c=_05d call kgpxug;
_0hp=_05d call kgcm9a;
if(_0c>=0&&_05d turretUnit _0hp==player)then{_05d action["UseWeapon",_05d,player,_0c];
kgu1o7=diag_tickTime;
kgmc8u=getPosWorld _05d;
};
};
};
kgfv3c=5;
["红色警告","导弹来袭！",false,5]call kgumf6;
};
};
};
kgszfv={kgc7c1=kgc7c1-[objNull];
{if!(_x in kgc7c1)then{_x call kgziqs;
};
}forEach kg6hor;
if(isServer)then{kgc7c1=kgc7c1+kg6hor;
publicVariable "kgc7c1";
};
kg6hor=[];
};
kgro74={_this params["_0f","_0ki"];
if(positionCameraToWorld[0,0,0]distance _0f>1000)then{[_0f]call(uiNamespace getVariable getText(configFile>>"CfgAmmo">>_0ki>>"muzzleEffect"));
kga73j=true;
};
};
kg1lqn={_08d=getPosATL _this select 2;
_this setVectorUp surfaceNormal getPosWorld _this;
if(local _this)then{_pos=getPosATL _this;
_pos set[2,_08d-(boundingCenter _this select 2)];
_this setPosATL _pos;
};
};
kgy2be=[["PylonWeapon_300Rnd_20mm_shells",500,"Plane_Fighter_03_base_F"]];
kg1y2o={private _0rp=getPylonMagazines _this;
{_x params["_0sp","_0ki","_0ec"];
if(_this isKindOf _0ec)then{{if(_x==_0sp)then{_this setAmmoOnPylon[_forEachIndex+1,_0ki];
};
}forEach _0rp;
};
}forEach kgy2be;
};
