/*
	ArmA 3 King of Hill
	Code written by Sa-Matra
	Using this code without Sa-Matra's direct permission is forbidden
	
	Special build for Gamed.de
	
	Build ETYKMBSIGDHGNALL
*/
#include "defines.hpp"
#include "sh_fl_generalFuncs.sqf"
kgpaxb=false;kgrh3c=[];kgxjs5=false;kgeeks=[];kgeyi9=false;kgedok=[];kg6ipw=[];kgqrwt=[[],[]];kgou3h=0;kgxm4g=[[],[]];kgj7su=0;kgu1o7=0;kgmc8u=[0,0,0];0 setWaves 1;0 setRainbow 1;if(isServer)then{kgvchw=[];kg9knh=[];kg75r3=[];publicVariable "kgvchw";publicVariable "kg9knh";publicVariable "kg75r3";kgiqgz=0;kgnfhp=[];publicVariable "kgnfhp";kgruzk=[];kg8n3l=[];kgnlkj=[];publicVariable "kgruzk";publicVariable "kg8n3l";publicVariable "kgnlkj";kgw1fg=0;kg7w7m=[];kgj2c8=[];kgcq5i=[];publicVariable "kg7w7m";publicVariable "kgj2c8";publicVariable "kgcq5i";kg65kr=0;kgc7c1=[];kg6hor=[];publicVariable "kgc7c1";publicVariable "kg6hor";};kgmbui=[];{call kg51kr}call kgy9dn;true spawn{waitUntil{!isNil{kg75r3}&&!isNil{kgnfhp}};sleep 1;{_x spawn{waitUntil{!isNil{missionNamespace getVariable _this}};(missionNamespace getVariable _this)call kgyn98;};}forEach kg75r3;};true spawn{waitUntil{!isNil{kgvchw}&&!isNil{kgnfhp}};sleep 1;kgvchw call kgyn98;};true spawn{waitUntil{!isNil{kgnlkj}};sleep 1;{_x spawn{waitUntil{!isNil{missionNamespace getVariable _this}};{_x allowDamage false;}forEach(missionNamespace getVariable _this);};}forEach kgnlkj;};true spawn{waitUntil{!isNil{kgruzk}};{_x allowDamage false;}forEach kgruzk;};true spawn{waitUntil{!isNil{kgcq5i}};sleep 1;{_x spawn{waitUntil{!isNil{missionNamespace getVariable _this}};{_x enableSimulation false;}forEach(missionNamespace getVariable _this);};}forEach kgcq5i;};true spawn{waitUntil{!isNil{kg7w7m}};{_x allowDamage false;}forEach kg7w7m;};true spawn{waitUntil{!isNil{kgc7c1}};{_x call kgziqs;}forEach kgc7c1;};"kg9knh" addPublicVariableEventHandler{(_this select 1)call kgyn98;};"kg8n3l" addPublicVariableEventHandler{call kgg65o;};"kgj2c8" addPublicVariableEventHandler{call kgfuqa;};"kg6hor" addPublicVariableEventHandler{call kgszfv};"kgmuca" addPublicVariableEventHandler{if(local(_this select 1))then{(_this select 1)lock true;};};"kgrzez" addPublicVariableEventHandler{if(local(_this select 1))then{(_this select 1)lock false;};};"kgv1le" addPublicVariableEventHandler{{if(local _x)then{_x lock false;};}forEach(_this select 1);};"kgkmdu" addPublicVariableEventHandler{if(local(_this select 1))then{(_this select 1)call kg592p;};};"kg1jf6" addPublicVariableEventHandler{(_this select 1)switchMove "AinvPknlMstpSnonWnonDnon_medic_1";};"kgrvge" addPublicVariableEventHandler{(_this select 1)call kgro74;};"kgw5ho" addPublicVariableEventHandler{(_this select 1)call kg1lqn;};