/*
	ArmA 3 King of Hill
	Code written by Sa-Matra
	Using this code without Sa-Matra's direct permission is forbidden
	
	Special build for Gamed.de
	
	Build ETYKMBSIGDHGNALL
*/
#include "hpp\idcs.hpp"
#include "hpp\defines.hpp"
kghpjg={if(isNil{_this})then{_this=true};
if(typeName _this!=typeName true)then{_this=true};
if(_this)then{_this=1}else{_this=-1};
player addRating(100000*_this-(rating player));
};
kggrxo={call kgulpn;
player setPosATL getPosATL(kghzyg select(kgubgt find playerSide)select 3);
call kgla5w;
call kgxcee;
true spawn kg7u5z;
true call kgyfwy;
true spawn kghr9n;
};
kgtiw9={call kgla5w;
call kgxcee;
true spawn kg7u5z;
true call kgyfwy;
true spawn kghr9n;
call kgi5e6;
};
kgi5e6={{call kg5n1o;
createDialog "KingOfHill_BuyAgain";
if(!kge24j)then{kge24j=true;
createDialog "KingOfHill_Rules";
};
}call kgx8et;
call kg88g7;
call kgulpn;
call kghpjg;
if(kg9po6)then{player setVariable["was_revived",false,true];
};
player setVariable["distance_reward_given_at",0,true];
kg9po6=false;
kgwynv=nil;
};
kgvazz={_0lm=["kgix91","kg3ghm","kgphc1","kghnak","kguyah","kgugc2","kgffee","kgha8x","kgigcy","kgmpgi"];
_0mm=_0lm select floor(random(count _0lm));
missionNamespace setVariable[_0mm,_this];
publicVariableServer _0mm;
};
kguq6u={7 cutFadeOut 1;
call kg3srb;
call kgzwbs;
player addWeapon "ItemGPS";
};
kgzwbs={private["_0nm","_0om","_0pg"];	//复活方法
_0nm=(kghznt select(kgubgt find playerSide));
_0om=ATLtoASL(_0nm modelToWorld[0,0,0]);
_0pg=ATLtoASL(_0nm modelToWorld[-1+random 1,-1+random 1,0]);
player switchMove "amovpercmstpslowwrfldnon";
player setPosASL _0pg;
player setDir(((_0om select 0)-(_0pg select 0))atan2((_0om select 1)-(_0pg select 1)));
player setVariable["koh_safe",serverTime,true];
player setVariable["ready",true,true];
};
kgx8et={[getPosATL(kghznt select(kgubgt find playerSide)),10,_this]call kgyzs8;
};
kg5n1o={private["_0pm"];
_0pm=getPosASL(kghznt select(kgubgt find playerSide));
_0pm set[2,(_0pm select 2)+0.91];
kg15v4=_0pm;
kgti9p="camera" createVehicleLocal(call kgnjbf);
call kg41pi;
kgti9p camSetTarget ASLtoATL(_0pm);
kgti9p cameraEffect["internal","back"];
kgkyng=true;
};
kg41pi={kgti9p camSetPos ASLtoATL(call kgnjbf);
kgti9p camCommit 0;
};
kgnjbf={private _pos=+kg15v4;
_pos set[0,(_pos select 0)+(sin(diag_tickTime*10))*20];
_pos set[1,(_pos select 1)+(cos(diag_tickTime*10))*20];
_pos set[2,(_pos select 2)+6];
_pos;
};
kg3srb={if(!isNil{kgti9p})then{kgti9p cameraEffect["terminate","back"];
camDestroy kgti9p;
deleteVehicle kgti9p;
};
kgkyng=false;
};
kg88g7={private["_05b","_pos"];
_05b=player;
if(isNil{kgvy66})then{kgvy66="Land_Pier_F" createVehicleLocal[0,0,0];
kgvy66 setPosASL[-15000,4000+random 4000,1+random 1];
kgvy66 setDir 0;
};
_pos=getPosASL kgvy66;
_pos set[2,(_pos select 2)+2];
_05b setPosASL _pos;
_05b switchMove "amovpercmstpslowwrfldnon";
};
kgulpn={private["_05b"];
_05b=player;
removeAllWeapons _05b;
removeUniform _05b;
removeVest _05b;
removeBackpack _05b;
removeHeadgear _05b;
removeGoggles _05b;
_05b removeWeapon(hmd _05b);
};
kg745x={private["_01p","_0o"];
_0o=_this select 0;
player setVariable["ready",false,true];
if(player getVariable["koh_assisted_by",-1]>0)then{player setVariable["koh_assisted_by",-1,true];
};
enableSentences false;
_this call kgrfrc;
if(!kg4bsk&&!kgkyng)then{kgo62w=_0o;
_0o call kg3788;
_0o call kg4d12;
};
};
kgg4sr={private["_09c","_0qm"];
_09c=_this select 0;
_0qm=_this select 1;
_09c addWeapon "ItemRadio";
player call kgvazz;
if(!kg4bsk&&!kgkyng)then{kg4bsk=true;
_0qm setVariable["revive_side",playerSide,true];
_0qm setVariable["revive_name",kgfmtd,true];
_0qm setVariable["revive_group",group player,true];
_0qm setVariable["revive_player",_09c,true];
kg74jq=_0qm;
private["_0je"];
_0je=_0qm getVariable["revive_goggles",""];
if(_0je!="")then{_0qm addGoggles _0je;
}else{removeGoggles _0qm;
};
if!(_0qm in kgonou)then{kgg215=_0qm;
publicVariableServer "kgg215";
};
}else{if(!isNull(kg74jq))then{kg74jq setVariable["revive_player",_09c,true];
kgg215=kg74jq;
publicVariableServer "kgg215";
};
};
player setVariable["ready",true,true];
player setVariable["koh_level",kgsoxm,true];
if!(player getVariable["show_me_on_map",true])then{player setVariable["show_me_on_map",false,true];
};
if(count(player getVariable["invites",[]])>0)then{player setVariable["invites",player getVariable["invites",[]],true];
};
call kgulpn;
call kg88g7;
call kgyfwy;
true spawn kghr9n;
};
kg3788={if(!isNil "kgsts9")then{deleteVehicle kgsts9};
private _0rm=[];
private _0sm=[];
{switch(true)do{case(_x select 0==primaryWeapon _0o):{_0rm=_x;
};
case(_x select 0==secondaryWeapon _0o):{_0sm=_x;
};
};
}forEach weaponsItems _0o;
if(count _0rm==0&&count _0sm==0)exitWith{objNull};
kgsts9={call kg7dkl}call kgisti;
kgsts9 setVariable["body",_this];
kgsts9 setVariable["primary",_0rm select 0];
kgsts9 setVariable["secondary",_0sm select 0];
_0o setVariable["revive_primary",_0rm];
_0o setVariable["revive_secondary",_0sm];
kgsts9;
};
kg7dkl={_0o=thisTrigger getVariable["body",objNull];
if(isNull _0o)exitWith{deleteVehicle thisTrigger};
if(player!=_0o&&!alive(_0o getVariable["revive_player",objNull]))exitWith{deleteVehicle thisTrigger};
if(isNil{thisTrigger getVariable "till"})exitWith{if(isNull objectParent _0o)then{
#ifdef kgm91g
format["REVIVE :: Start"]call kghgjw;

#endif
thisTrigger setVariable["till",diag_tickTime+5];
};
};
if(diag_tickTime>=thisTrigger getVariable["till",diag_tickTime])exitWith{
#ifdef kgm91g
format["REVIVE :: Search timed out!"]call kghgjw;

#endif
deleteVehicle thisTrigger;
};
_0tm=nearestObjects[_0o,["WeaponHolderSimulated"],20]select{local _x};
_0rm=thisTrigger getVariable["primary",""];
if(_0rm!="")then{{if(weaponCargo _x select 0==_0rm)exitWith{
#ifdef kgm91g
format["REVIVE :: Primary %1 in %2",_0rm,netid _x]call kghgjw;

#endif
_x setVariable["body",_0o,true];
_0o setVariable["revive_primary_wh",_x];
thisTrigger setVariable["revive_primary",""];
_0rm="";
}}forEach _0tm;
};
_0sm=thisTrigger getVariable["secondary",""];
if(_0sm!="")then{{if(weaponCargo _x select 0==_0sm)exitWith{
#ifdef kgm91g
format["REVIVE :: Secondary %1 in %2",_0sm,netid _x]call kghgjw;

#endif
_x setVariable["body",_0o,true];
_0o setVariable["revive_secondary_wh",_x];
thisTrigger setVariable["revive_secondary",""];
_0sm="";
}}forEach _0tm;
};
if(_0rm==""&&_0sm=="")exitWith{
#ifdef kgm91g
format["REVIVE :: Search successful!"]call kghgjw;

#endif
deleteVehicle thisTrigger;
};
};
kgrw4u={private["_0o","_0bc","_0bd","_assigned","_items","_0be","_0ce","_backpack","_headgear","_0je","_handgun","_handgun_items","_0rm","_primary_wh","_0sm","_secondary_wh"];
_0o=_this;
player switchMove "amovppnemstpsnonwnondnon";
_0um=getUnitLoadout _0o;
{_x params["_0v","_0vm"];
if(!isNull _0vm&&_0o!=_0vm)then{if((_0v select 0)in weaponCargo _0vm)then{if(count _0v<7)then{_0v set[6,_0v select 5];
_0v set[5,[]];
};
_0um set[_forEachIndex,_0v];
deleteVehicle _0vm;
};
};
}forEach[[_0o getVariable["revive_primary",[]],_0o getVariable["revive_primary_wh",objNull]],[_0o getVariable["revive_secondary",[]],_0o getVariable["revive_secondary_wh",objNull]]];
player setUnitLoadout _0um;
call kglj4j;
_0f={if(_0o in crew _x)exitWith{_x}}forEach vehicles;
if(isNil{_0f})then{_0f=objNull};
if(!isNull(_0f))then{_0f deleteVehicleCrew _0o;
if!(player moveInAny _0f)then{player setPosATL getPosATL _0o;
};
}else{player setPosATL getPosATL _0o;
player setDir getDir _0o;
deleteVehicle _0o;
};
player setVariable["was_revived",true,true];
player setDamage 0.4;
call kga7r2;
kg4bsk=false;
kg7gij=player;
player setVariable["ready",true,true];
if(!kg9po6)then{if((getPosATL player)call kgfnsu)then{[[player getVariable["koh_owner",0],kg94c4]]call kgt98j;
};
};
if(_0o getVariable["koh_revived_by",0]>0)then{player setVariable["koh_assisted_by",_0o getVariable["koh_revived_by",0],true];
};
kg9po6=true;
};
kgg4on={kg4bsk=false;
kgyoy5=kg74jq;
publicVariable "kgyoy5";
kg74jq setVariable["revive_player",objNull,true];
kg74jq=objNull;
true spawn{if(true)then{kg5471=true;
kgydqi=diag_tickTime+7;
8 cutRsc["KingOfHill_RespawnIn","PLAIN",0.00001];
call kgakvw;
kgkyng=true;
_0ra=1;
RscNoise_color=[1,1,1,0.5];
4 cutText["","BLACK",_0ra];
5 cutRsc["RscNoise","PLAIN",0.00001];
waitUntil{diag_tickTime>kgydqi};
8 cutFadeOut 0;
kg5471=false;
};
call kgxqcw;
call kga7r2;
if(missionNamespace getVariable["kgv6hy",sideUnknown]!=side group player&&missionNamespace getVariable["kgv6hy",sideUnknown]!=sideUnknown&&call kgz9vh&&call kgrtml)exitWith{kg6vgc=kgv6hy;
kgt6f5=[player,kg6vgc];
publicVariableServer "kgt6f5";
kgv6hy=sideUnknown;
publicVariable "kgv6hy";
if(isServer&&!isDedicated)then{publicVariableServer "kgv6hy";
};
kg2dt7=player;
publicVariableServer "kg2dt7";
createDialog "KingOfHill_Teambalance";
};
4 cutFadeOut 1;
5 cutFadeOut 1;
6 cutFadeOut 1;
call kgi5e6;
};
};

#define kgi6cz	(60 * 20)
kgz9vh={if(diag_tickTime-kgzrd7>kgi6cz)exitWith{false};
if(count(units group player)>1&&count(units group player)<=6)exitWith{false};
if({alive(_x select 0)}count kg8u9s>0)exitWith{false};
true;
};
kgrtml={private["_08l","_0me"];
_08l=0;
{_0me=_x;
_08l=_08l max({side group _x==_0me}count kgnine);
}forEach kgubgt;
_0me=side group player;
{side group _x==_0me}count kgnine==_08l;
};
kglhkj={private "_0wm";
_0wm=_this displayCtrl kgo48e;
_0wm ctrlSetStructuredText parseText format[localize "STR_KOH_TeamBalance_Text2",localize format["STR_KOH_Gen_Team%1_2",kg6vgc]];
call kgywjw;
true spawn{sleep 15;
(uiNamespace getVariable "KingOfHill_Teambalance")closeDisplay 1;
};
};
kgita7={call kg46sc;
};
kg46sc={endMission(switch(kg6vgc)do{case blufor:{"LockedToBLUFOR"};
case opfor:{"LockedToOPFOR"};
case independent:{"LockedToIndep"};
default{"LOSER"};
});
};
kga7r2={if(!isNil{kgzixc})then{8 cutFadeOut 0;
kgzixc cameraEffect["terminate","back"];
camDestroy kgzixc;
deleteVehicle kgzixc;
};
};
kg4d12={if(kgskxp==kgze3i)exitWith{};
private["_0mh"];
_0mh=positionCameraToWorld[0,0,0];
_0mh set[2,(_0mh select 2)+1];
call kga7r2;
showCinemaBorder true;
kgzixc="camera" createVehicleLocal _0mh;
kgzixc setPos _0mh;
kgzixc camSetTarget _this;
kgzixc camCommit 0;
kgzixc cameraEffect["internal","back"];
8 cutRsc["KingOfHill_ReviveStuff","PLAIN",0.00001];
_this spawn{sleep 1;
private["_0xm"];
_0xm=time+30;
waitUntil{([0,0,0]vectorDistance(velocity _this)==0)||time>_0xm};
sleep 1;
if(!kg4bsk)exitWith{};
if(isNull(_this))exitWith{};
private["_0zm","_0ym"];
_0ym=_this modelToWorld(_this selectionPosition "neck");
_0zm=+_0ym;
_0zm set[0,(_0zm select 0)+0.1];
_0zm set[1,(_0zm select 1)+0.1];
_0zm set[2,(_0zm select 2)+1.5];
kgzixc camSetPos _0zm;
kgzixc camSetTarget _0ym;
kgzixc camCommit 2;
};
_this spawn{waitUntil{floor(((_this selectionPosition "pelvis")select 2)*100000)==11996||isNull(_this)};
if(isNull(_this))exitWith{};
_this switchMove "Static_Dead";
_this setPosATL getPosATL _this;
if(((getPosATL _this)select 2)<0.1)then{sleep 1;
_this setVectorUp(surfaceNormal(getPosATL _this));
};
};
disableSerialization;
private["_0a","_0ef","_0uf"];
_0a=uiNamespace getVariable "KingOfHill_ReviveStuff";
_0ef=_0a displayCtrl kgkkco;
_0ef ctrlAddEventHandler["Draw",{[_this,true]call kgxbru}];
call kgictd;
(_0a displayCtrl kg9v48)ctrlShow false;
};
kgictd={_0a=uiNamespace getVariable["KingOfHill_ReviveStuff",displayNull];
_0ef=_0a displayCtrl kgkkco;
if(isNull(_0ef)||isNull(kgo62w))exitWith{};
_0ef ctrlMapAnimAdd[0,kg8l2f select kgyv5m,getPosATL kgo62w];
ctrlMapAnimCommit _0ef;
};
kg1gfu={kgyv5m=kgyv5m+1;
if(kgyv5m==count kg8l2f)then{kgyv5m=0};
call kgictd;
};
kg7npo={disableSerialization;
private["_0a"];
_0a=uiNamespace getVariable "KingOfHill_ReviveStuff";
if(isNil{if(isNull(_0a))then{nil}else{true}})exitWith{};
params["_09m","_0jn","_01m","_0en","_0hn","_0kn"];
_01m params["_0in","_0fn","_0ln","_0gn","_0mn","_09b","_0g","_0me"];
(_0a displayCtrl kg9v48)ctrlShow true;
_02m=_0a displayCtrl kgwji3;
_03m=_0a displayCtrl kg3noz;
_04m=_0a displayCtrl kgeslg;
_05m=_0a displayCtrl kgc1xi;
_06m=_0a displayCtrl kg7dsy;
_07m=_0a displayCtrl kgxikm;
_08m=squadParams(_this select 1);
if(!_09m&&!isStreamFriendlyUIEnabled&&count _08m>0)then{_0an=_0a displayCtrl kgna5f;
_0bn=_0a displayCtrl kg3chp;
_0cn=_0a displayCtrl kgvoil;
_0dn=(_08m select 0 select 4);
_04e=[];
_04e pushBack(_08m select 0 select 1);
_04e pushBack(_08m select 0 select 5);
_04e pushBack(_08m select 0 select 3);
_04e pushBack(_08m select 1 select 1);
_04e pushBack(_08m select 1 select 5);
_04e=_04e-["","N/A"];
if(count _04e<=0&&_0dn=="")exitWith{_0an ctrlShow false;
};
_0bn ctrlSetText _0dn;
_0cn ctrlSetStructuredText parseText(_04e joinString "<br/>");
};
_02m ctrlSetStructuredText parseText(switch(true)do{case(_09m):{"You were <t color='#ff0000'>teamkilled</t> by:"};
case(!_0en):{"You were indirectly killed by:"};
default{"杀死你的玩家:"};
});
_03m ctrlSetText(if(_0me in[blufor,opfor,independent])then{_0me call kgrrdk}else{""});
_04m ctrlSetText(if(_0g>0)then{str _0g}else{""});
_05m ctrlSetText(if(isStreamFriendlyUIEnabled)then{if(_09m)then{if(_0fn==group player)then{localize "STR_KOH_Groupmate"}else{localize "STR_KOH_Teammate"};
}else{localize "STR_KOH_Enemy"};
}else{_0gn});
if(!(settings_gameType==kgfcbl&&settings_disableKilledByWeaponAndDistance)&&true)then{if(_0en)then{_06m ctrlSetStructuredText text(if(_0hn)then{"你被此载具撞死:";
}else{format["%1%2",switch(true)do{case(_09b<=100):{"Less than 100 meters"};
case(_09b>1000):{format["Over more than %1 meters",floor(_09b/1000)*1000]};
case(_09b>100):{format["Over %1 meters",floor(_09b/100)*100]};
default{format["超过 %1 米",floor(_09b/10)*10]};
},if(_0en)then{"，使用武器:"}else{"."}];
});
_07m ctrlSetStructuredText parseText(if((_0in!=_0jn&&!_0kn)||_0hn)then{format["%1<br/><img image='%2' size='2.5'/>",getText(configFile>>"CfgVehicles">>_0ln>>"displayname"),getText(configFile>>"CfgVehicles">>_0ln>>"picture")];
}else{format["%1<br/><img image='%2' size='3.5'/>",getText(configFile>>"CfgWeapons">>_0mn>>"displayname"),getText(configFile>>"CfgWeapons">>_0mn>>"picture")];
});
};
};
};
kg29ca={disableSerialization;
private["_0a"];
_0a=uiNamespace getVariable "KingOfHill_ReviveStuff";
if(isNil{if(isNull(_0a))then{nil}else{true}})exitWith{};
if(!isNull(_this select 1)&&!isNil{_this select 7})then{private["_02m","_03m","_04m","_05m","_06m","_07m","_0an","_0bn","_0cn","_09b"];
(_0a displayCtrl kg9v48)ctrlShow true;
_02m=_0a displayCtrl kgwji3;
_03m=_0a displayCtrl kg3noz;
_04m=_0a displayCtrl kgeslg;
_05m=_0a displayCtrl kgc1xi;
_06m=_0a displayCtrl kg7dsy;
_07m=_0a displayCtrl kgxikm;
_0an=_0a displayCtrl kgna5f;
_0bn=_0a displayCtrl kg3chp;
_0cn=_0a displayCtrl kgvoil;
_08m=squadParams(_this select 1);
if(!(_this select 9)&&count(_08m)>0&&{(_08m select 0 select 4)!=""})then{_04e=[];
_04e pushBack(_08m select 0 select 1);
_04e pushBack(_08m select 0 select 5);
_04e pushBack(_08m select 0 select 3);
_04e pushBack(_08m select 1 select 1);
_04e pushBack(_08m select 1 select 5);
for "_i" from 0 to count(_04e)-1 do{_04e deleteAt(_04e find "");
_04e deleteAt(_04e find "N/A")};
_0bn ctrlSetText(_08m select 0 select 4);
_0cn ctrlSetStructuredText parseText(_04e joinString "<br/>");
}else{_0an ctrlShow false;
};
_09b=_this select 8;
_0nn=_this select 10;
_0hn=_this select 11;
_02m ctrlSetStructuredText parseText(switch(true)do{case(_this select 9):{"You were <t color='#ff0000'>teamkilled</t> by:"};
case(_this select 10):{"You were indirectly killed by:"};
default{"杀死你的玩家:"};
});
_03m ctrlSetText(switch(true)do{case((_this select 4)in[blufor,opfor,independent]):{(_this select 4)call kgrrdk};
default{""};
});
_04m ctrlSetText(switch(true)do{case(_this select 5>0):{str(_this select 5)};
default{""};
});
_05m ctrlSetText(_this select 7);
if!(settings_gameType==kgfcbl&&settings_disableKilledByWeaponAndDistance)then{if(!_0nn)then{_06m ctrlSetStructuredText text(if(_0hn)then{"They ran you over with:"}else{format["%1%2",switch(true)do{case(_09b<=100):{"Less than 100 meters"};
case(_09b>1000):{format["Over more than %1 meters",floor(_09b/1000)*1000]};
case(_09b>100):{format["Over %1 meters",floor(_09b/100)*100]};
default{format["超过 %1 米",floor(_09b/10)*10]};
},if(!_0nn)then{"，使用武器:"}else{"."}]});
_07m ctrlSetStructuredText parseText(if((!isNull(_this select 2)&&(_this select 1)!=(_this select 2))||_0hn)then{format["%1<br/><img image='%2' size='2.5'/>",getText(configFile>>"CfgVehicles">>(_this select 3)>>"displayname"),getText(configFile>>"CfgVehicles">>(_this select 3)>>"picture")];
}else{format["%1<br/><img image='%2' size='3.5'/>",getText(configFile>>"CfgWeapons">>(_this select 6)>>"displayname"),getText(configFile>>"CfgWeapons">>(_this select 6)>>"picture")];
});
};
};
};
};
kgakvw={true spawn{disableSerialization;
private["_0a","_0on"];
_0a=uiNamespace getVariable "KingOfHill_RespawnIn";
_0on=_0a displayCtrl kgs7lq;
while{(kgydqi-diag_tickTime)>=0}do{if(isNil{if(isNull(_0a))then{nil}else{true}})exitWith{};
_0on ctrlSetText format["%1 %2%3",localize "STR_KOH_Gen_RespawnInUppercase",ceil(kgydqi-diag_tickTime)max 0,"_"];
};
};
private["_0pn","_0qn"];
_0pn=[];
for "_i" from 0 to count(kg6mxp)-1 do{if(call(kg6mxp select _i select 0)&&_i!=kg6un5)then{for "_j" from 1 to(kg6mxp select _i select 1)do{_0pn set[count _0pn,_i];
};
};
};
kg6un5=(_0pn select floor(random(count _0pn)));
_0qn=kg6mxp select kg6un5;
disableSerialization;
private["_0a","_0sn","_0rn"];
_0a=uiNamespace getVariable "KingOfHill_RespawnIn";
_0rn=_0a displayCtrl kg99nh;
_0sn=_0a displayCtrl kg4goe;
if(isNil{if(isNull(_0a))then{nil}else{true}})exitWith{};
_0rn ctrlSetText(_0qn select 2);
_0sn ctrlSetStructuredText parseText format["<t size='2'>%1</t><br/>%2",_0qn select 3,_0qn select 4];
};
kg6un5=-1;
kg6mxp=[[{true},10,"i\hint_icons.paa",localize "STR_KOH_Hint_IconsWindowsKey",localize "STR_KOH_Hint_IconsWindowsKeyText"],[{true},10,"i\hint_jetrearm.paa",localize "STR_KOH_Hint_JetRearm",localize "STR_KOH_Hint_JetRearmText"],[{true},10,"i\hint_gestures.paa",localize "STR_KOH_Hint_Gestures",localize "STR_KOH_Hint_GesturesText"]];
